import { Toaster } from 'react-hot-toast'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='pt-BR' data-theme='forest'>
      <body className={inter.className}>
        <div>
          <Toaster
            toastOptions={{
              style: {
                borderRadius: '10px',
                background: '#1C1C1C',
                color: '#fff',
              },
            }}
          />
        </div>
        {children}
      </body>
    </html>
  )
}
